const pictograms = [
    // Acciones y Verbos
    { id: 1, text: 'Correr', icon: 'streamline-ux:running', category: 'Acciones y Verbos' },
    { id: 2, text: 'Saltar', icon: 'streamline-ux:jumping', category: 'Acciones y Verbos' },
    { id: 3, text: 'Nadar', icon: 'streamline-ux:swimming', category: 'Acciones y Verbos' },
    { id: 4, text: 'Escribir', icon: 'streamline-ux:pencil-write', category: 'Acciones y Verbos' },
    { id: 5, text: 'Leer', icon: 'streamline-ux:book-read', category: 'Acciones y Verbos' },
    { id: 6, text: 'Cantar', icon: 'streamline-ux:music-note-2', category: 'Acciones y Verbos' },
    { id: 7, text: 'Bailar', icon: 'streamline-ux:love-it-couple', category: 'Acciones y Verbos' },
    { id: 8, text: 'Dormir', icon: 'streamline-ux:sleep', category: 'Acciones y Verbos' },
    { id: 9, text: 'Despertar', icon: 'streamline-ux:alarm-clock', category: 'Acciones y Verbos' },
    { id: 10, text: 'Abrazar', icon: 'streamline-ux:love-it-couple', category: 'Acciones y Verbos' },
    { id: 11, text: 'Besar', icon: 'streamline-ux:love-it-couple-kiss', category: 'Acciones y Verbos' },
    { id: 12, text: 'Llorar', icon: 'streamline-ux:sad', category: 'Acciones y Verbos' },
    { id: 13, text: 'Reír', icon: 'streamline-ux:happy', category: 'Acciones y Verbos' },
    { id: 14, text: 'Jugar', icon: 'streamline-ux:game-controler', category: 'Acciones y Verbos' },
    { id: 15, text: 'Comer', icon: 'streamline-ux:food-kitchen-utensils-fork-spoon', category: 'Acciones y Verbos' },
    { id: 16, text: 'Beber', icon: 'streamline-ux:drink-glass-cocktail', category: 'Acciones y Verbos' },
    { id: 17, text: 'Ir', icon: 'streamline-ux:walking', category: 'Acciones y Verbos' },
    { id: 18, text: 'Ver', icon: 'streamline-ux:eye', category: 'Acciones y Verbos' },
    { id: 19, text: 'Escuchar', icon: 'streamline-ux:ear', category: 'Acciones y Verbos' },
    { id: 20, text: 'Hablar', icon: 'streamline-ux:bubble-chat', category: 'Acciones y Verbos' },
    { id: 21, text: 'Pensar', icon: 'streamline-ux:idea', category: 'Acciones y Verbos' },
    { id: 22, text: 'Sentir', icon: 'streamline-ux:heart', category: 'Acciones y Verbos' },
    { id: 23, text: 'Ayudar', icon: 'streamline-ux:help-question-mark', category: 'Acciones y Verbos' },
    { id: 24, text: 'Trabajar', icon: 'streamline-ux:work-briefcase', category: 'Acciones y Verbos' },
    { id: 25, text: 'Estudiar', icon: 'streamline-ux:book', category: 'Acciones y Verbos' },

    // Animales
    { id: 26, text: 'Perro', icon: 'streamline-ux:dog', category: 'Animales' },
    { id: 27, text: 'Gato', icon: 'streamline-ux:cat', category: 'Animales' },
    { id: 28, text: 'Pájaro', icon: 'streamline-ux:bird', category: 'Animales' },
    { id: 29, text: 'Pez', icon: 'streamline-ux:fish', category: 'Animales' },
    { id: 30, text: 'Caballo', icon: 'streamline-ux:horse', category: 'Animales' },
    { id: 31, text: 'Vaca', icon: 'streamline-ux:cow', category: 'Animales' },
    { id: 32, text: 'León', icon: 'streamline-ux:lion', category: 'Animales' },
    { id: 33, text: 'Tigre', icon: 'streamline-ux:tiger', category: 'Animales' },
    { id: 34, text: 'Oso', icon: 'streamline-ux:bear', category: 'Animales' },
    { id: 35, text: 'Elefante', icon: 'streamline-ux:elephant', category: 'Animales' },
    { id: 36, text: 'Jirafa', icon: 'streamline-ux:giraffe', category: 'Animales' },
    { id: 37, text: 'Mono', icon: 'streamline-ux:monkey', category: 'Animales' },
    { id: 38, text: 'Serpiente', icon: 'streamline-ux:snake', category: 'Animales' },
    { id: 39, text: 'Cocodrilo', icon: 'streamline-ux:crocodile', category: 'Animales' },
    { id: 40, text: 'Rana', icon: 'streamline-ux:frog', category: 'Animales' },
    { id: 41, text: 'Mariposa', icon: 'streamline-ux:butterfly', category: 'Animales' },
    { id: 42, text: 'Abeja', icon: 'streamline-ux:bee', category: 'Animales' },
    { id: 43, text: 'Araña', icon: 'streamline-ux:spider', category: 'Animales' },
    { id: 44, text: 'Delfín', icon: 'streamline-ux:dolphin', category: 'Animales' },
    { id: 45, text: 'Ballena', icon: 'streamline-ux:whale', category: 'Animales' },

    // Comida
    { id: 46, text: 'Manzana', icon: 'streamline-ux:food-apple', category: 'Comida' },
    { id: 47, text: 'Plátano', icon: 'streamline-ux:food-banana', category: 'Comida' },
    { id: 48, text: 'Naranja', icon: 'streamline-ux:food-orange', category: 'Comida' },
    { id: 49, text: 'Fresa', icon: 'streamline-ux:food-strawberry', category: 'Comida' },
    { id: 50, text: 'Uva', icon: 'streamline-ux:food-grapes', category: 'Comida' },
    { id: 51, text: 'Sandía', icon: 'streamline-ux:food-watermelon', category: 'Comida' },
    { id: 52, text: 'Pan', icon: 'streamline-ux:food-bread', category: 'Comida' },
    { id: 53, text: 'Queso', icon: 'streamline-ux:food-cheese', category: 'Comida' },
    { id: 54, text: 'Huevo', icon: 'streamline-ux:food-egg', category: 'Comida' },
    { id: 55, text: 'Pollo', icon: 'streamline-ux:food-chicken', category: 'Comida' },
    { id: 56, text: 'Carne', icon: 'streamline-ux:food-meat', category: 'Comida' },
    { id: 57, text: 'Pescado', icon: 'streamline-ux:food-fish', category: 'Comida' },
    { id: 58, text: 'Arroz', icon: 'streamline-ux:food-rice', category: 'Comida' },
    { id: 59, text: 'Pasta', icon: 'streamline-ux:food-spaghetti', category: 'Comida' },
    { id: 60, text: 'Pizza', icon: 'streamline-ux:food-pizza', category: 'Comida' },
    { id: 61, text: 'Hamburguesa', icon: 'streamline-ux:food-hamburger', category: 'Comida' },
    { id: 62, text: 'Papas fritas', icon: 'streamline-ux:food-french-fries', category: 'Comida' },
    { id: 63, text: 'Helado', icon: 'streamline-ux:food-ice-cream', category: 'Comida' },
    { id: 64, text: 'Pastel', icon: 'streamline-ux:food-cake', category: 'Comida' },
    { id: 65, text: 'Galleta', icon: 'streamline-ux:food-cookie', category: 'Comida' },
    { id: 66, text: 'Leche', icon: 'streamline-ux:drink-milk-bottle', category: 'Comida' },
    { id: 67, text: 'Jugo', icon: 'streamline-ux:drink-juice-box', category: 'Comida' },
    { id: 68, text: 'Agua', icon: 'streamline-ux:drink-water-glass', category: 'Comida' },

    // Ropa
    { id: 69, text: 'Camisa', icon: 'streamline-ux:clothing-shirt', category: 'Ropa' },
    { id: 70, text: 'Pantalón', icon: 'streamline-ux:clothing-trousers', category: 'Ropa' },
    { id: 71, text: 'Vestido', icon: 'streamline-ux:clothing-dress', category: 'Ropa' },
    { id: 72, text: 'Falda', icon: 'streamline-ux:clothing-skirt', category: 'Ropa' },
    { id: 73, text: 'Zapatos', icon: 'streamline-ux:clothing-shoes', category: 'Ropa' },
    { id: 74, text: 'Calcetines', icon: 'streamline-ux:clothing-socks', category: 'Ropa' },
    { id: 75, text: 'Sombrero', icon: 'streamline-ux:clothing-hat', category: 'Ropa' },
    { id: 76, text: 'Chaqueta', icon: 'streamline-ux:clothing-jacket', category: 'Ropa' },
    { id: 77, text: 'Gafas', icon: 'streamline-ux:eye-glasses', category: 'Ropa' },

    // Partes del cuerpo
    { id: 78, text: 'Cabeza', icon: 'streamline-ux:head', category: 'Partes del cuerpo' },
    { id: 79, text: 'Ojo', icon: 'streamline-ux:eye', category: 'Partes del cuerpo' },
    { id: 80, text: 'Nariz', icon: 'streamline-ux:nose', category: 'Partes del cuerpo' },
    { id: 81, text: 'Boca', icon: 'streamline-ux:mouth', category: 'Partes del cuerpo' },
    { id: 82, text: 'Oreja', icon: 'streamline-ux:ear', category: 'Partes del cuerpo' },
    { id: 83, text: 'Mano', icon: 'streamline-ux:hand', category: 'Partes del cuerpo' },
    { id: 84, text: 'Pie', icon: 'streamline-ux:foot', category: 'Partes del cuerpo' },
    { id: 85, text: 'Brazo', icon: 'streamline-ux:arm', category: 'Partes del cuerpo' },
    { id: 86, text: 'Pierna', icon: 'streamline-ux:leg', category: 'Partes del cuerpo' },
    { id: 87, text: 'Pelo', icon: 'streamline-ux:hair', category: 'Partes del cuerpo' },

    // Lugares
    { id: 88, text: 'Casa', icon: 'streamline-ux:house', category: 'Lugares' },
    { id: 89, text: 'Escuela', icon: 'streamline-ux:school', category: 'Lugares' },
    { id: 90, text: 'Parque', icon: 'streamline-ux:park', category: 'Lugares' },
    { id: 91, text: 'Tienda', icon: 'streamline-ux:shop', category: 'Lugares' },
    { id: 92, text: 'Hospital', icon: 'streamline-ux:hospital', category: 'Lugares' },
    { id: 93, text: 'Playa', icon: 'streamline-ux:beach-parasol', category: 'Lugares' },
    { id: 94, text: 'Cine', icon: 'streamline-ux:cinema', category: 'Lugares' },
    { id: 95, text: 'Restaurante', icon: 'streamline-ux:restaurant', category: 'Lugares' },
    { id: 96, text: 'Supermercado', icon: 'streamline-ux:shopping-cart', category: 'Lugares' },
    { id: 97, text: 'Zoológico', icon: 'streamline-ux:zoo', category: 'Lugares' },
    { id: 98, text: 'Biblioteca', icon: 'streamline-ux:library', category: 'Lugares' },
    { id: 99, text: 'Iglesia', icon: 'streamline-ux:church', category: 'Lugares' },
    { id: 100, text: 'Montaña', icon: 'streamline-ux:mountain', category: 'Lugares' },
    { id: 101, text: 'Río', icon: 'streamline-ux:river', category: 'Lugares' },
    { id: 102, text: 'Mar', icon: 'streamline-ux:sea', category: 'Lugares' },

    // Emociones
    { id: 103, text: 'Feliz', icon: 'streamline-ux:happy', category: 'Emociones' },
    { id: 104, text: 'Triste', icon: 'streamline-ux:sad', category: 'Emociones' },
    { id: 105, text: 'Enojado', icon: 'streamline-ux:angry', category: 'Emociones' },
    { id: 106, text: 'Asustado', icon: 'streamline-ux:scared', category: 'Emociones' },
    { id: 107, text: 'Sorprendido', icon: 'streamline-ux:surprised', category: 'Emociones' },
    { id: 108, text: 'Cansado', icon: 'streamline-ux:tired', category: 'Emociones' },
    { id: 109, text: 'Aburrido', icon: 'streamline-ux:bored', category: 'Emociones' },
    { id: 110, text: 'Enamorado', icon: 'streamline-ux:in-love', category: 'Emociones' },
    { id: 111, text: 'Contento', icon: 'streamline-ux:happy', category: 'Emociones' },

    // Colores
    { id: 112, text: 'Rojo', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 113, text: 'Azul', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 114, text: 'Verde', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 115, text: 'Amarillo', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 116, text: 'Naranja', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 117, text: 'Morado', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 118, text: 'Rosa', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 119, text: 'Blanco', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 120, text: 'Negro', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 121, text: 'Gris', icon: 'streamline-ux:color-picker', category: 'Colores' },
    { id: 122, text: 'Marrón', icon: 'streamline-ux:color-picker', category: 'Colores' },

    // Números
    { id: 123, text: 'Uno', icon: 'streamline-ux:number-1', category: 'Números' },
    { id: 124, text: 'Dos', icon: 'streamline-ux:number-2', category: 'Números' },
    { id: 125, text: 'Tres', icon: 'streamline-ux:number-3', category: 'Números' },
    { id: 126, text: 'Cuatro', icon: 'streamline-ux:number-4', category: 'Números' },
    { id: 127, text: 'Cinco', icon: 'streamline-ux:number-5', category: 'Números' },
    { id: 128, text: 'Seis', icon: 'streamline-ux:number-6', category: 'Números' },
    { id: 129, text: 'Siete', icon: 'streamline-ux:number-7', category: 'Números' },
    { id: 130, text: 'Ocho', icon: 'streamline-ux:number-8', category: 'Números' },
    { id: 131, text: 'Nueve', icon: 'streamline-ux:number-9', category: 'Números' },
    { id: 132, text: 'Diez', icon: 'streamline-ux:number-10', category: 'Números' },

    // Familia
    { id: 133, text: 'Mamá', icon: 'streamline-ux:woman-1', category: 'Familia' },
    { id: 134, text: 'Papá', icon: 'streamline-ux:man-1', category: 'Familia' },
    { id: 135, text: 'Hermano', icon: 'streamline-ux:boy-1', category: 'Familia' },
    { id: 136, text: 'Hermana', icon: 'streamline-ux:girl-1', category: 'Familia' },
    { id: 137, text: 'Abuelo', icon: 'streamline-ux:old-man', category: 'Familia' },
    { id: 138, text: 'Abuela', icon: 'streamline-ux:old-woman', category: 'Familia' },
    { id: 139, text: 'Bebé', icon: 'streamline-ux:baby', category: 'Familia' },

    // Juguetes
    { id: 140, text: 'Pelota', icon: 'streamline-ux:ball-sport', category: 'Juguetes' },
    { id: 141, text: 'Muñeca', icon: 'streamline-ux:doll', category: 'Juguetes' },
    { id: 142, text: 'Coche', icon: 'streamline-ux:car-toy', category: 'Juguetes' },
    { id: 143, text: 'Tren', icon: 'streamline-ux:train-toy', category: 'Juguetes' },
    { id: 144, text: 'Avión', icon: 'streamline-ux:plane-toy', category: 'Juguetes' },
    { id: 145, text: 'Barco', icon: 'streamline-ux:boat-toy', category: 'Juguetes' },
    { id: 146, text: 'Bicicleta', icon: 'streamline-ux:bicycle-toy', category: 'Juguetes' },
    { id: 147, text: 'Bloques', icon: 'streamline-ux:blocks-toy', category: 'Juguetes' },
    { id: 148, text: 'Rompecabezas', icon: 'streamline-ux:puzzle-toy', category: 'Juguetes' },

    // Naturaleza
    { id: 149, text: 'Sol', icon: 'streamline-ux:sun', category: 'Naturaleza' },
    { id: 150, text: 'Luna', icon: 'streamline-ux:moon', category: 'Naturaleza' },
    { id: 151, text: 'Estrella', icon: 'streamline-ux:star', category: 'Naturaleza' },
    { id: 152, text: 'Árbol', icon: 'streamline-ux:tree', category: 'Naturaleza' },
    { id: 153, text: 'Flor', icon: 'streamline-ux:flower', category: 'Naturaleza' },
    { id: 154, text: 'Nube', icon: 'streamline-ux:cloud', category: 'Naturaleza' },
    { id: 155, text: 'Lluvia', icon: 'streamline-ux:rain', category: 'Naturaleza' },
    { id: 156, text: 'Nieve', icon: 'streamline-ux:snow', category: 'Naturaleza' },
    { id: 157, text: 'Viento', icon: 'streamline-ux:wind', category: 'Naturaleza' },
    { id: 158, text: 'Fuego', icon: 'streamline-ux:fire', category: 'Naturaleza' },

    // Profesiones
    { id: 159, text: 'Doctor', icon: 'streamline-ux:doctor', category: 'Profesiones' },
    { id: 160, text: 'Enfermera', icon: 'streamline-ux:nurse', category: 'Profesiones' },
    { id: 161, text: 'Maestro', icon: 'streamline-ux:teacher', category: 'Profesiones' },
    { id: 162, text: 'Policía', icon: 'streamline-ux:policeman', category: 'Profesiones' },
    { id: 163, text: 'Bombero', icon: 'streamline-ux:fireman', category: 'Profesiones' },
    { id: 164, text: 'Cocinero', icon: 'streamline-ux:chef', category: 'Profesiones' },
    { id: 165, text: 'Piloto', icon: 'streamline-ux:pilot', category: 'Profesiones' },
    { id: 166, text: 'Músico', icon: 'streamline-ux:musician', category: 'Profesiones' },
    { id: 167, text: 'Pintor', icon: 'streamline-ux:painter', category: 'Profesiones' },
    { id: 168, text: 'Carpintero', icon: 'streamline-ux:carpenter', category: 'Profesiones' },

    // Transporte
    { id: 169, text: 'Coche', icon: 'streamline-ux:car', category: 'Transporte' },
    { id: 170, text: 'Autobús', icon: 'streamline-ux:bus', category: 'Transporte' },
    { id: 171, text: 'Tren', icon: 'streamline-ux:train', category: 'Transporte' },
    { id: 172, text: 'Avión', icon: 'streamline-ux:plane', category: 'Transporte' },
    { id: 173, text: 'Barco', icon: 'streamline-ux:boat', category: 'Transporte' },
    { id: 174, text: 'Bicicleta', icon: 'streamline-ux:bicycle', category: 'Transporte' },
    { id: 175, text: 'Moto', icon: 'streamline-ux:motorcycle', category: 'Transporte' },
    { id: 176, text: 'Taxi', icon: 'streamline-ux:taxi', category: 'Transporte' },
    { id: 177, text: 'Ambulancia', icon: 'streamline-ux:ambulance', category: 'Transporte' },
    { id: 178, text: 'Camión de bomberos', icon: 'streamline-ux:fire-truck', category: 'Transporte' },

    // Adjetivos
    { id: 179, text: 'Grande', icon: 'streamline-ux:expand', category: 'Adjetivos' },
    { id: 180, text: 'Pequeño', icon: 'streamline-ux:compress', category: 'Adjetivos' },
    { id: 181, text: 'Alto', icon: 'streamline-ux:arrow-up', category: 'Adjetivos' },
    { id: 182, text: 'Bajo', icon: 'streamline-ux:arrow-down', category: 'Adjetivos' },
    { id: 183, text: 'Rápido', icon: 'streamline-ux:shipping-fast', category: 'Adjetivos' },
    { id: 184, text: 'Lento', icon: 'streamline-ux:shipping-slow', category: 'Adjetivos' },
    { id: 185, text: 'Caliente', icon: 'streamline-ux:hot-temperature', category: 'Adjetivos' },
    { id: 186, text: 'Frío', icon: 'streamline-ux:cold-temperature', category: 'Adjetivos' },
    { id: 187, text: 'Limpio', icon: 'streamline-ux:soap', category: 'Adjetivos' },
    { id: 188, text: 'Sucio', icon: 'streamline-ux:bug', category: 'Adjetivos' },
    { id: 189, text: 'Duro', icon: 'streamline-ux:rock', category: 'Adjetivos' },
    { id: 190, text: 'Blando', icon: 'streamline-ux:feather', category: 'Adjetivos' },
    { id: 191, text: 'Bonito', icon: 'streamline-ux:bling', category: 'Adjetivos' },
    { id: 192, text: 'Feo', icon: 'streamline-ux:monster', category: 'Adjetivos' },

    // Conceptos
    { id: 193, text: 'Sí', icon: 'streamline-ux:check-circle', category: 'Conceptos' },
    { id: 194, text: 'No', icon: 'streamline-ux:close-circle', category: 'Conceptos' },
    { id: 195, text: 'Hola', icon: 'streamline-ux:hand-wave', category: 'Conceptos' },
    { id: 196, text: 'Adiós', icon: 'streamline-ux:hand-wave', category: 'Conceptos' },
    { id: 197, text: 'Por favor', icon: 'streamline-ux:pray', category: 'Conceptos' },
    { id: 198, text: 'Gracias', icon: 'streamline-ux:handshake', category: 'Conceptos' },
    { id: 199, text: 'Lo siento', icon: 'streamline-ux:sad', category: 'Conceptos' },
    { id: 200, text: 'Ayuda', icon: 'streamline-ux:help-question-mark', category: 'Conceptos' },
    { id: 201, text: 'Más', icon: 'streamline-ux:add', category: 'Conceptos' },
    { id: 202, text: 'Menos', icon: 'streamline-ux:subtract', category: 'Conceptos' },
    { id: 203, text: 'Igual', icon: 'streamline-ux:equal', category: 'Conceptos' },
    { id: 204, text: 'Diferente', icon: 'streamline-ux:not-equal', category: 'Conceptos' },
    { id: 205, text: 'Ahora', icon: 'streamline-ux:clock', category: 'Conceptos' },
    { id: 206, text: 'Después', icon: 'streamline-ux:arrow-right', category: 'Conceptos' },
    { id: 207, text: 'Antes', icon: 'streamline-ux:arrow-left', category: 'Conceptos' },

    // Preguntas
    { id: 208, text: '¿Qué?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },
    { id: 209, text: '¿Quién?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },
    { id: 210, text: '¿Cuándo?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },
    { id: 211, text: '¿Dónde?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },
    { id: 212, text: '¿Por qué?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },
    { id: 213, text: '¿Cómo?', icon: 'streamline-ux:help-question-mark', category: 'Preguntas' },

    // Formas
    { id: 214, text: 'Círculo', icon: 'streamline-ux:circle', category: 'Formas' },
    { id: 215, text: 'Cuadrado', icon: 'streamline-ux:square', category: 'Formas' },
    { id: 216, text: 'Triángulo', icon: 'streamline-ux:triangle', category: 'Formas' },
    { id: 217, text: 'Rectángulo', icon: 'streamline-ux:rectangle', category: 'Formas' },
    { id: 218, text: 'Estrella', icon: 'streamline-ux:star', category: 'Formas' },
    { id: 219, text: 'Corazón', icon: 'streamline-ux:heart', category: 'Formas' },

    // Días de la semana
    { id: 220, text: 'Lunes', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 221, text: 'Martes', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 222, text: 'Miércoles', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 223, text: 'Jueves', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 224, text: 'Viernes', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 225, text: 'Sábado', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },
    { id: 226, text: 'Domingo', icon: 'streamline-ux:calendar-day', category: 'Días de la semana' },

    // Meses del año
    { id: 227, text: 'Enero', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 228, text: 'Febrero', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 229, text: 'Marzo', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 230, text: 'Abril', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 231, text: 'Mayo', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 232, text: 'Junio', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 233, text: 'Julio', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 234, text: 'Agosto', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 235, text: 'Septiembre', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 236, text: 'Octubre', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 237, text: 'Noviembre', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },
    { id: 238, text: 'Diciembre', icon: 'streamline-ux:calendar-month', category: 'Meses del año' },

    // Clima
    { id: 239, text: 'Soleado', icon: 'streamline-ux:sun', category: 'Clima' },
    { id: 240, text: 'Nublado', icon: 'streamline-ux:cloud', category: 'Clima' },
    { id: 241, text: 'Lluvioso', icon: 'streamline-ux:rain', category: 'Clima' },
    { id: 242, text: 'Nevando', icon: 'streamline-ux:snow', category: 'Clima' },
    { id: 243, text: 'Viento', icon: 'streamline-ux:wind', category: 'Clima' },
    { id: 244, text: 'Tormenta', icon: 'streamline-ux:storm', category: 'Clima' },

    // Objetos de la casa
    { id: 245, text: 'Mesa', icon: 'streamline-ux:table', category: 'Objetos de la casa' },
    { id: 246, text: 'Silla', icon: 'streamline-ux:chair', category: 'Objetos de la casa' },
    { id: 247, text: 'Cama', icon: 'streamline-ux:bed', category: 'Objetos de la casa' },
    { id: 248, text: 'Sofá', icon: 'streamline-ux:sofa', category: 'Objetos de la casa' },
    { id: 249, text: 'Lámpara', icon: 'streamline-ux:lamp', category: 'Objetos de la casa' },
    { id: 250, text: 'Televisión', icon: 'streamline-ux:tv', category: 'Objetos de la casa' },
    { id: 251, text: 'Teléfono', icon: 'streamline-ux:phone', category: 'Objetos de la casa' },
    { id: 252, text: 'Ordenador', icon: 'streamline-ux:laptop', category: 'Objetos de la casa' },
    { id: 253, text: 'Puerta', icon: 'streamline-ux:door', category: 'Objetos de la casa' },
    { id: 254, text: 'Ventana', icon: 'streamline-ux:window', category: 'Objetos de la casa' },
    { id: 255, text: 'Baño', icon: 'streamline-ux:toilet', category: 'Objetos de la casa' },
    { id: 256, text: 'Cocina', icon: 'streamline-ux:kitchen', category: 'Objetos de la casa' },
    { id: 257, text: 'Jardín', icon: 'streamline-ux:garden', category: 'Objetos de la casa' },

    // Material escolar
    { id: 258, text: 'Lápiz', icon: 'streamline-ux:pencil', category: 'Material escolar' },
    { id: 259, text: 'Goma', icon: 'streamline-ux:eraser', category: 'Material escolar' },
    { id: 260, text: 'Sacapuntas', icon: 'streamline-ux:sharpener', category: 'Material escolar' },
    { id: 261, text: 'Regla', icon: 'streamline-ux:ruler', category: 'Material escolar' },
    { id: 262, text: 'Tijeras', icon: 'streamline-ux:scissors', category: 'Material escolar' },
    { id: 263, text: 'Pegamento', icon: 'streamline-ux:glue', category: 'Material escolar' },
    { id: 264, text: 'Libro', icon: 'streamline-ux:book', category: 'Material escolar' },
    { id: 265, text: 'Cuaderno', icon: 'streamline-ux:notebook', category: 'Material escolar' },
    { id: 266, text: 'Mochila', icon: 'streamline-ux:backpack', category: 'Material escolar' },
    { id: 267, text: 'Pizarra', icon: 'streamline-ux:blackboard', category: 'Material escolar' },

    // Bebidas
    { id: 268, text: 'Agua', icon: 'streamline-ux:drink-water-glass', category: 'Bebidas' },
    { id: 269, text: 'Leche', icon: 'streamline-ux:drink-milk-bottle', category: 'Bebidas' },
    { id: 270, text: 'Jugo', icon: 'streamline-ux:drink-juice-box', category: 'Bebidas' },
    { id: 271, text: 'Refresco', icon: 'streamline-ux:drink-soda-can', category: 'Bebidas' },
    { id: 272, text: 'Té', icon: 'streamline-ux:drink-tea-cup', category: 'Bebidas' },
    { id: 273, text: 'Café', icon: 'streamline-ux:drink-coffee-cup', category: 'Bebidas' },

    // Postres
    { id: 274, text: 'Pastel', icon: 'streamline-ux:food-cake', category: 'Postres' },
    { id: 275, text: 'Helado', icon: 'streamline-ux:food-ice-cream', category: 'Postres' },
    { id: 276, text: 'Galleta', icon: 'streamline-ux:food-cookie', category: 'Postres' },
    { id: 277, text: 'Chocolate', icon: 'streamline-ux:food-chocolate', category: 'Postres' },
    { id: 278, text: 'Caramelo', icon: 'streamline-ux:food-candy', category: 'Postres' },
    { id: 279, text: 'Fruta', icon: 'streamline-ux:food-apple', category: 'Postres' },

    // Instrumentos musicales
    { id: 280, text: 'Guitarra', icon: 'streamline-ux:music-guitar', category: 'Instrumentos musicales' },
    { id: 281, text: 'Piano', icon: 'streamline-ux:music-piano', category: 'Instrumentos musicales' },
    { id: 282, text: 'Batería', icon: 'streamline-ux:music-drums', category: 'Instrumentos musicales' },
    { id: 283, text: 'Violín', icon: 'streamline-ux:music-violin', category: 'Instrumentos musicales' },
    { id: 284, text: 'Trompeta', icon: 'streamline-ux:music-trumpet', category: 'Instrumentos musicales' },
    { id: 285, text: 'Flauta', icon: 'streamline-ux:music-flute', category: 'Instrumentos musicales' },

    // Deportes
    { id: 286, text: 'Fútbol', icon: 'streamline-ux:sport-soccer', category: 'Deportes' },
    { id: 287, text: 'Baloncesto', icon: 'streamline-ux:sport-basketball', category: 'Deportes' },
    { id: 288, text: 'Béisbol', icon: 'streamline-ux:sport-baseball', category: 'Deportes' },
    { id: 289, text: 'Tenis', icon: 'streamline-ux:sport-tennis', category: 'Deportes' },
    { id: 290, text: 'Natación', icon: 'streamline-ux:sport-swimming', category: 'Deportes' },
    { id: 291, text: 'Atletismo', icon: 'streamline-ux:sport-running', category: 'Deportes' },
    { id: 292, text: 'Ciclismo', icon: 'streamline-ux:sport-cycling', category: 'Deportes' },

    // Sentimientos
    { id: 293, text: 'Amor', icon: 'streamline-ux:heart', category: 'Sentimientos' },
    { id: 294, text: 'Amistad', icon: 'streamline-ux:love-it-couple', category: 'Sentimientos' },
    { id: 295, text: 'Alegría', icon: 'streamline-ux:happy', category: 'Sentimientos' },
    { id: 296, text: 'Tristeza', icon: 'streamline-ux:sad', category: 'Sentimientos' },
    { id: 297, text: 'Miedo', icon: 'streamline-ux:scared', category: 'Sentimientos' },
    { id: 298, text: 'Ira', icon: 'streamline-ux:angry', category: 'Sentimientos' },
    { id: 299, text: 'Sorpresa', icon: 'streamline-ux:surprised', category: 'Sentimientos' },
    { id: 300, text: 'Confianza', icon: 'streamline-ux:trust', category: 'Sentimientos' },
    { id: 301, text: 'Vergüenza', icon: 'streamline-ux:shy', category: 'Sentimientos' },
];
