const pictograms = [
    // Acciones y Verbos
    { id: 1, text: 'Correr', icon: 'bi bi-person-running', category: 'Acciones y Verbos' },
    { id: 2, text: 'Saltar', icon: 'bi bi-person-bounding-box', category: 'Acciones y Verbos' },
    { id: 3, text: 'Nadar', icon: 'bi bi-person-arms-up', category: 'Acciones y Verbos' },
    { id: 4, text: 'Escribir', icon: 'bi bi-pencil', category: 'Acciones y Verbos' },
    { id: 5, text: 'Leer', icon: 'bi bi-book', category: 'Acciones y Verbos' },
    { id: 6, text: 'Cantar', icon: 'bi bi-mic', category: 'Acciones y Verbos' },
    { id: 7, text: 'Bailar', icon: 'bi bi-music-note-beamed', category: 'Acciones y Verbos' },
    { id: 8, text: 'Dormir', icon: 'bi bi-moon-stars', category: 'Acciones y Verbos' },
    { id: 9, text: 'Despertar', icon: 'bi bi-sun', category: 'Acciones y Verbos' },
    { id: 10, text: 'Abrazar', icon: 'bi bi-person-hearts', category: 'Acciones y Verbos' },
    { id: 11, text: 'Besar', icon: 'bi bi-hearts', category: 'Acciones y Verbos' },
    { id: 12, text: 'Llorar', icon: 'bi bi-emoji-frown', category: 'Acciones y Verbos' },
    { id: 13, text: 'Reír', icon: 'bi bi-emoji-smile', category: 'Acciones y Verbos' },
    { id: 14, text: 'Jugar', icon: 'bi bi-joystick', category: 'Acciones y Verbos' },
    { id: 15, text: 'Comer', icon: 'bi bi-egg-fried', category: 'Acciones y Verbos' },
    { id: 16, text: 'Beber', icon: 'bi bi-cup-straw', category: 'Acciones y Verbos' },
    { id: 17, text: 'Ir', icon: 'bi bi-person-walking', category: 'Acciones y Verbos' },
    { id: 18, text: 'Ver', icon: 'bi bi-eye', category: 'Acciones y Verbos' },
    { id: 19, text: 'Escuchar', icon: 'bi bi-ear', category: 'Acciones y Verbos' },
    { id: 20, text: 'Hablar', icon: 'bi bi-chat-dots', category: 'Acciones y Verbos' },
    { id: 21, text: 'Pensar', icon: 'bi bi-lightbulb', category: 'Acciones y Verbos' },
    { id: 22, text: 'Sentir', icon: 'bi bi-heart', category: 'Acciones y Verbos' },
    { id: 23, text: 'Ayudar', icon: 'bi bi-person-plus', category: 'Acciones y Verbos' },
    { id: 24, text: 'Trabajar', icon: 'bi bi-briefcase', category: 'Acciones y Verbos' },
    { id: 25, text: 'Estudiar', icon: 'bi bi-book-half', category: 'Acciones y Verbos' },

    // Animales
    { id: 26, text: 'Perro', icon: 'bi bi-dog', category: 'Animales' },
    { id: 27, text: 'Gato', icon: 'bi bi-cat', category: 'Animales' },
    { id: 28, text: 'Pájaro', icon: 'bi bi-twitter', category: 'Animales' },
    { id: 29, text: 'Pez', icon: 'bi bi-fish', category: 'Animales' },
    { id: 30, text: 'Caballo', icon: 'bi bi-horse', category: 'Animales' },
    { id: 31, text: 'Vaca', icon: 'bi bi-cow', category: 'Animales' },
    { id: 32, text: 'León', icon: 'bi bi-lion', category: 'Animales' },
    { id: 33, text: 'Tigre', icon: 'bi bi-tiger', category: 'Animales' },
    { id: 34, text: 'Oso', icon: 'bi bi-bear', category: 'Animales' },
    { id: 35, text: 'Elefante', icon: 'bi bi-elephant', category: 'Animales' },
    { id: 36, text: 'Jirafa', icon: 'bi bi-giraffe', category: 'Animales' },
    { id: 37, text: 'Mono', icon: 'bi bi-monkey', category: 'Animales' },
    { id: 38, text: 'Serpiente', icon: 'bi bi-snake', category: 'Animales' },
    { id: 39, text: 'Cocodrilo', icon: 'bi bi-crocodile', category: 'Animales' },
    { id: 40, text: 'Rana', icon: 'bi bi-frog', category: 'Animales' },
    { id: 41, text: 'Mariposa', icon: 'bi bi-bug', category: 'Animales' },
    { id: 42, text: 'Abeja', icon: 'bi bi-bee', category: 'Animales' },
    { id: 43, text: 'Araña', icon: 'bi bi-spider', category: 'Animales' },
    { id: 44, text: 'Delfín', icon: 'bi bi-dolphin', category: 'Animales' },
    { id: 45, text: 'Ballena', icon: 'bi bi-whale', category: 'Animales' },

    // Comida
    { id: 46, text: 'Manzana', icon: 'bi bi-apple', category: 'Comida' },
    { id: 47, text: 'Plátano', icon: 'bi bi-banana', category: 'Comida' },
    { id: 48, text: 'Naranja', icon: 'bi bi-orange', category: 'Comida' },
    { id: 49, text: 'Fresa', icon: 'bi bi-strawberry', category: 'Comida' },
    { id: 50, text: 'Uva', icon: 'bi bi-grapes', category: 'Comida' },
    { id: 51, text: 'Sandía', icon: 'bi bi-watermelon', category: 'Comida' },
    { id: 52, text: 'Pan', icon: 'bi bi-bread-slice', category: 'Comida' },
    { id: 53, text: 'Queso', icon: 'bi bi-cheese', category: 'Comida' },
    { id: 54, text: 'Huevo', icon: 'bi bi-egg', category: 'Comida' },
    { id: 55, text: 'Pollo', icon: 'bi bi-chicken', category: 'Comida' },
    { id: 56, text: 'Carne', icon: 'bi bi-meat', category: 'Comida' },
    { id: 57, text: 'Pescado', icon: 'bi bi-fish', category: 'Comida' },
    { id: 58, text: 'Arroz', icon: 'bi bi-egg-fried', category: 'Comida' },
    { id: 59, text: 'Pasta', icon: 'bi bi-egg-fried', category: 'Comida' },
    { id: 60, text: 'Pizza', icon: 'bi bi-pizza', category: 'Comida' },
    { id: 61, text: 'Hamburguesa', icon: 'bi bi-hamburger', category: 'Comida' },
    { id: 62, text: 'Papas fritas', icon: 'bi bi-french-fries', category: 'Comida' },
    { id: 63, text: 'Helado', icon: 'bi bi-ice-cream', category: 'Comida' },
    { id: 64, text: 'Pastel', icon: 'bi bi-cake', category: 'Comida' },
    { id: 65, text: 'Galleta', icon: 'bi bi-cookie', category: 'Comida' },
    { id: 66, text: 'Leche', icon: 'bi bi-cup-straw', category: 'Comida' },
    { id: 67, text: 'Jugo', icon: 'bi bi-cup-straw', category: 'Comida' },
    { id: 68, text: 'Agua', icon: 'bi bi-cup-straw', category: 'Comida' },

    // Ropa
    { id: 69, text: 'Camisa', icon: 'bi bi-t-shirt', category: 'Ropa' },
    { id: 70, text: 'Pantalón', icon: 'bi bi-pants', category: 'Ropa' },
    { id: 71, text: 'Vestido', icon: 'bi bi-dress', category: 'Ropa' },
    { id: 72, text: 'Falda', icon: 'bi bi-skirt', category: 'Ropa' },
    { id: 73, text: 'Zapatos', icon: 'bi bi-shoe-prints', category: 'Ropa' },
    { id: 74, text: 'Calcetines', icon: 'bi bi-socks', category: 'Ropa' },
    { id: 75, text: 'Sombrero', icon: 'bi bi-hat', category: 'Ropa' },
    { id: 76, text: 'Chaqueta', icon: 'bi bi-jacket', category: 'Ropa' },
    { id: 77, text: 'Gafas', icon: 'bi bi-eyeglasses', category: 'Ropa' },

    // Partes del cuerpo
    { id: 78, text: 'Cabeza', icon: 'bi bi-person-circle', category: 'Partes del cuerpo' },
    { id: 79, text: 'Ojo', icon: 'bi bi-eye', category: 'Partes del cuerpo' },
    { id: 80, text: 'Nariz', icon: 'bi bi-nose', category: 'Partes del cuerpo' },
    { id: 81, text: 'Boca', icon: 'bi bi-mouth', category: 'Partes del cuerpo' },
    { id: 82, text: 'Oreja', icon: 'bi bi-ear', category: 'Partes del cuerpo' },
    { id: 83, text: 'Mano', icon: 'bi bi-hand-index-thumb', category: 'Partes del cuerpo' },
    { id: 84, text: 'Pie', icon: 'bi bi-footprints', category: 'Partes del cuerpo' },
    { id: 85, text: 'Brazo', icon: 'bi bi-person-arms-up', category: 'Partes del cuerpo' },
    { id: 86, text: 'Pierna', icon: 'bi bi-person-walking', category: 'Partes del cuerpo' },
    { id: 87, text: 'Pelo', icon: 'bi bi-person-vcard', category: 'Partes del cuerpo' },

    // Lugares
    { id: 88, text: 'Casa', icon: 'bi bi-house', category: 'Lugares' },
    { id: 89, text: 'Escuela', icon: 'bi bi-building', category: 'Lugares' },
    { id: 90, text: 'Parque', icon: 'bi bi-tree', category: 'Lugares' },
    { id: 91, text: 'Tienda', icon: 'bi bi-shop', category: 'Lugares' },
    { id: 92, text: 'Hospital', icon: 'bi bi-hospital', category: 'Lugares' },
    { id: 93, text: 'Playa', icon: 'bi bi-beach', category: 'Lugares' },
    { id: 94, text: 'Cine', icon: 'bi bi-film', category: 'Lugares' },
    { id: 95, text: 'Restaurante', icon: 'bi bi-restaurant', category: 'Lugares' },
    { id: 96, text: 'Supermercado', icon: 'bi bi-cart', category: 'Lugares' },
    { id: 97, text: 'Zoológico', icon: 'bi bi-panda', category: 'Lugares' },
    { id: 98, text: 'Biblioteca', icon: 'bi bi-bookshelf', category: 'Lugares' },
    { id: 99, text: 'Iglesia', icon: 'bi bi-church', category: 'Lugares' },
    { id: 100, text: 'Montaña', icon: 'bi bi-mountain', category: 'Lugares' },
    { id: 101, text: 'Río', icon: 'bi bi-water', category: 'Lugares' },
    { id: 102, text: 'Mar', icon: 'bi bi-water', category: 'Lugares' },

    // Emociones
    { id: 103, text: 'Feliz', icon: 'bi bi-emoji-laughing', category: 'Emociones' },
    { id: 104, text: 'Triste', icon: 'bi bi-emoji-dizzy', category: 'Emociones' },
    { id: 105, text: 'Enojado', icon: 'bi bi-emoji-angry', category: 'Emociones' },
    { id: 106, text: 'Asustado', icon: 'bi bi-emoji-scream', category: 'Emociones' },
    { id: 107, text: 'Sorprendido', icon: 'bi bi-emoji-surprise', category: 'Emociones' },
    { id: 108, text: 'Cansado', icon: 'bi bi-emoji-sleepy', category: 'Emociones' },
    { id: 109, text: 'Aburrido', icon: 'bi bi-emoji-neutral', category: 'Emociones' },
    { id: 110, text: 'Enamorado', icon: 'bi bi-emoji-heart-eyes', category: 'Emociones' },
    { id: 111, text: 'Contento', icon: 'bi bi-emoji-smile', category: 'Emociones' },

    // Colores
    { id: 112, text: 'Rojo', icon: 'bi bi-palette', category: 'Colores' },
    { id: 113, text: 'Azul', icon: 'bi bi-palette', category: 'Colores' },
    { id: 114, text: 'Verde', icon: 'bi bi-palette', category: 'Colores' },
    { id: 115, text: 'Amarillo', icon: 'bi bi-palette', category: 'Colores' },
    { id: 116, text: 'Naranja', icon: 'bi bi-palette', category: 'Colores' },
    { id: 117, text: 'Morado', icon: 'bi bi-palette', category: 'Colores' },
    { id: 118, text: 'Rosa', icon: 'bi bi-palette', category: 'Colores' },
    { id: 119, text: 'Blanco', icon: 'bi bi-palette', category: 'Colores' },
    { id: 120, text: 'Negro', icon: 'bi bi-palette', category: 'Colores' },
    { id: 121, text: 'Gris', icon: 'bi bi-palette', category: 'Colores' },
    { id: 122, text: 'Marrón', icon: 'bi bi-palette', category: 'Colores' },

    // Números
    { id: 123, text: 'Uno', icon: 'bi bi-1-circle', category: 'Números' },
    { id: 124, text: 'Dos', icon: 'bi bi-2-circle', category: 'Números' },
    { id: 125, text: 'Tres', icon: 'bi bi-3-circle', category: 'Números' },
    { id: 126, text: 'Cuatro', icon: 'bi bi-4-circle', category: 'Números' },
    { id: 127, text: 'Cinco', icon: 'bi bi-5-circle', category: 'Números' },
    { id: 128, text: 'Seis', icon: 'bi bi-6-circle', category: 'Números' },
    { id: 129, text: 'Siete', icon: 'bi bi-7-circle', category: 'Números' },
    { id: 130, text: 'Ocho', icon: 'bi bi-8-circle', category: 'Números' },
    { id: 131, text: 'Nueve', icon: 'bi bi-9-circle', category: 'Números' },
    { id: 132, text: 'Diez', icon: 'bi bi-10-circle', category: 'Números' },

    // Familia
    { id: 133, text: 'Mamá', icon: 'bi bi-person-female', category: 'Familia' },
    { id: 134, text: 'Papá', icon: 'bi bi-person-male', category: 'Familia' },
    { id: 135, text: 'Hermano', icon: 'bi bi-person', category: 'Familia' },
    { id: 136, text: 'Hermana', icon: 'bi bi-person', category: 'Familia' },
    { id: 137, text: 'Abuelo', icon: 'bi bi-person-vcard', category: 'Familia' },
    { id: 138, text: 'Abuela', icon: 'bi bi-person-vcard', category: 'Familia' },
    { id: 139, text: 'Bebé', icon: 'bi bi-person-arms-up', category: 'Familia' },

    // Juguetes
    { id: 140, text: 'Pelota', icon: 'bi bi-baseball', category: 'Juguetes' },
    { id: 141, text: 'Muñeca', icon: 'bi bi-person-standing-dress', category: 'Juguetes' },
    { id: 142, text: 'Coche', icon: 'bi bi-car-front', category: 'Juguetes' },
    { id: 143, text: 'Tren', icon: 'bi bi-train-front', category: 'Juguetes' },
    { id: 144, text: 'Avión', icon: 'bi bi-airplane', category: 'Juguetes' },
    { id: 145, text: 'Barco', icon: 'bi bi-boat', category: 'Juguetes' },
    { id: 146, text: 'Bicicleta', icon: 'bi bi-bicycle', category: 'Juguetes' },
    { id: 147, text: 'Bloques', icon: 'bi bi-bricks', category: 'Juguetes' },
    { id: 148, text: 'Rompecabezas', icon: 'bi bi-puzzle', category: 'Juguetes' },

    // Naturaleza
    { id: 149, text: 'Sol', icon: 'bi bi-sun', category: 'Naturaleza' },
    { id: 150, text: 'Luna', icon: 'bi bi-moon', category: 'Naturaleza' },
    { id: 151, text: 'Estrella', icon: 'bi bi-star', category: 'Naturaleza' },
    { id: 152, text: 'Árbol', icon: 'bi bi-tree', category: 'Naturaleza' },
    { id: 153, text: 'Flor', icon: 'bi bi-flower1', category: 'Naturaleza' },
    { id: 154, text: 'Nube', icon: 'bi bi-cloud', category: 'Naturaleza' },
    { id: 155, text: 'Lluvia', icon: 'bi bi-cloud-rain', category: 'Naturaleza' },
    { id: 156, text: 'Nieve', icon: 'bi bi-snow', category: 'Naturaleza' },
    { id: 157, text: 'Viento', icon: 'bi bi-wind', category: 'Naturaleza' },
    { id: 158, text: 'Fuego', icon: 'bi bi-fire', category: 'Naturaleza' },

    // Profesiones
    { id: 159, text: 'Doctor', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 160, text: 'Enfermera', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 161, text: 'Maestro', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 162, text: 'Policía', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 163, text: 'Bombero', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 164, text: 'Cocinero', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 165, text: 'Piloto', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 166, text: 'Músico', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 167, text: 'Pintor', icon: 'bi bi-person-vcard', category: 'Profesiones' },
    { id: 168, text: 'Carpintero', icon: 'bi bi-person-vcard', category: 'Profesiones' },

    // Transporte
    { id: 169, text: 'Coche', icon: 'bi bi-car-front', category: 'Transporte' },
    { id: 170, text: 'Autobús', icon: 'bi bi-bus-front', category: 'Transporte' },
    { id: 171, text: 'Tren', icon: 'bi bi-train-front', category: 'Transporte' },
    { id: 172, text: 'Avión', icon: 'bi bi-airplane', category: 'Transporte' },
    { id: 173, text: 'Barco', icon: 'bi bi-boat', category: 'Transporte' },
    { id: 174, text: 'Bicicleta', icon: 'bi bi-bicycle', category: 'Transporte' },
    { id: 175, text: 'Moto', icon: 'bi bi-bicycle', category: 'Transporte' },
    { id: 176, text: 'Taxi', icon: 'bi bi-taxi-front', category: 'Transporte' },
    { id: 177, text: 'Ambulancia', icon: 'bi bi-truck-front', category: 'Transporte' },
    { id: 178, text: 'Camión de bomberos', icon: 'bi bi-truck-front', category: 'Transporte' },

    // Adjetivos
    { id: 179, text: 'Grande', icon: 'bi bi-arrows-angle-expand', category: 'Adjetivos' },
    { id: 180, text: 'Pequeño', icon: 'bi bi-arrows-angle-contract', category: 'Adjetivos' },
    { id: 181, text: 'Alto', icon: 'bi bi-arrow-up-short', category: 'Adjetivos' },
    { id: 182, text: 'Bajo', icon: 'bi bi-arrow-down-short', category: 'Adjetivos' },
    { id: 183, text: 'Rápido', icon: 'bi bi-fast-forward', category: 'Adjetivos' },
    { id: 184, text: 'Lento', icon: 'bi bi-rewind', category: 'Adjetivos' },
    { id: 185, text: 'Caliente', icon: 'bi bi-thermometer-high', category: 'Adjetivos' },
    { id: 186, text: 'Frío', icon: 'bi bi-thermometer-low', category: 'Adjetivos' },
    { id: 187, text: 'Limpio', icon: 'bi bi-droplet-half', category: 'Adjetivos' },
    { id: 188, text: 'Sucio', icon: 'bi bi-trash', category: 'Adjetivos' },
    { id: 189, text: 'Duro', icon: 'bi bi-gem', category: 'Adjetivos' },
    { id: 190, text: 'Blando', icon: 'bi bi-cloud-drizzle', category: 'Adjetivos' },
    { id: 191, text: 'Bonito', icon: 'bi bi-emoji-wink', category: 'Adjetivos' },
    { id: 192, text: 'Feo', icon: 'bi bi-emoji-expressionless', category: 'Adjetivos' },

    // Conceptos
    { id: 193, text: 'Sí', icon: 'bi bi-check-lg', category: 'Conceptos' },
    { id: 194, text: 'No', icon: 'bi bi-x-lg', category: 'Conceptos' },
    { id: 195, text: 'Hola', icon: 'bi bi-hand-thumbs-up', category: 'Conceptos' },
    { id: 196, text: 'Adiós', icon: 'bi bi-hand-thumbs-down', category: 'Conceptos' },
    { id: 197, text: 'Por favor', icon: 'bi bi-person-raised-hand', category: 'Conceptos' },
    { id: 198, text: 'Gracias', icon: 'bi bi-person-check', category: 'Conceptos' },
    { id: 199, text: 'Lo siento', icon: 'bi bi-person-exclamation', category: 'Conceptos' },
    { id: 200, text: 'Ayuda', icon: 'bi bi-question-circle', category: 'Conceptos' },
    { id: 201, text: 'Más', icon: 'bi bi-plus-lg', category: 'Conceptos' },
    { id: 202, text: 'Menos', icon: 'bi bi-dash-lg', category: 'Conceptos' },
    { id: 203, text: 'Igual', icon: 'bi bi-equals', category: 'Conceptos' },
    { id: 204, text: 'Diferente', icon: 'bi bi-not-equal', category: 'Conceptos' },
    { id: 205, text: 'Ahora', icon: 'bi bi-clock', category: 'Conceptos' },
    { id: 206, text: 'Después', icon: 'bi bi-arrow-right-short', category: 'Conceptos' },
    { id: 207, text: 'Antes', icon: 'bi bi-arrow-left-short', category: 'Conceptos' },

    // Preguntas
    { id: 208, text: '¿Qué?', icon: 'bi bi-question-lg', category: 'Preguntas' },
    { id: 209, text: '¿Quién?', icon: 'bi bi-question-lg', category: 'Preguntas' },
    { id: 210, text: '¿Cuándo?', icon: 'bi bi-question-lg', category: 'Preguntas' },
    { id: 211, text: '¿Dónde?', icon: 'bi bi-question-lg', category: 'Preguntas' },
    { id: 212, text: '¿Por qué?', icon: 'bi bi-question-lg', category: 'Preguntas' },
    { id: 213, text: '¿Cómo?', icon: 'bi bi-question-lg', category: 'Preguntas' },

    // Formas
    { id: 214, text: 'Círculo', icon: 'bi bi-circle', category: 'Formas' },
    { id: 215, text: 'Cuadrado', icon: 'bi bi-square', category: 'Formas' },
    { id: 216, text: 'Triángulo', icon: 'bi bi-triangle', category: 'Formas' },
    { id: 217, text: 'Rectángulo', icon: 'bi bi-rectangle', category: 'Formas' },
    { id: 218, text: 'Estrella', icon: 'bi bi-star', category: 'Formas' },
    { id: 219, text: 'Corazón', icon: 'bi bi-heart', category: 'Formas' },

    // Días de la semana
    { id: 220, text: 'Lunes', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 221, text: 'Martes', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 222, text: 'Miércoles', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 223, text: 'Jueves', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 224, text: 'Viernes', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 225, text: 'Sábado', icon: 'bi bi-calendar-day', category: 'Días de la semana' },
    { id: 226, text: 'Domingo', icon: 'bi bi-calendar-day', category: 'Días de la semana' },

    // Meses del año
    { id: 227, text: 'Enero', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 228, text: 'Febrero', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 229, text: 'Marzo', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 230, text: 'Abril', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 231, text: 'Mayo', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 232, text: 'Junio', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 233, text: 'Julio', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 234, text: 'Agosto', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 235, text: 'Septiembre', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 236, text: 'Octubre', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 237, text: 'Noviembre', icon: 'bi bi-calendar-month', category: 'Meses del año' },
    { id: 238, text: 'Diciembre', icon: 'bi bi-calendar-month', category: 'Meses del año' },

    // Clima
    { id: 239, text: 'Soleado', icon: 'bi bi-sun', category: 'Clima' },
    { id: 240, text: 'Nublado', icon: 'bi bi-cloud', category: 'Clima' },
    { id: 241, text: 'Lluvioso', icon: 'bi bi-cloud-rain', category: 'Clima' },
    { id: 242, text: 'Nevando', icon: 'bi bi-snow', category: 'Clima' },
    { id: 243, text: 'Viento', icon: 'bi bi-wind', category: 'Clima' },
    { id: 244, text: 'Tormenta', icon: 'bi bi-cloud-lightning-rain', category: 'Clima' },

    // Objetos de la casa
    { id: 245, text: 'Mesa', icon: 'bi bi-table', category: 'Objetos de la casa' },
    { id: 246, text: 'Silla', icon: 'bi bi-chair', category: 'Objetos de la casa' },
    { id: 247, text: 'Cama', icon: 'bi bi-bed', category: 'Objetos de la casa' },
    { id: 248, text: 'Sofá', icon: 'bi bi-sofa', category: 'Objetos de la casa' },
    { id: 249, text: 'Lámpara', icon: 'bi bi-lightbulb', category: 'Objetos de la casa' },
    { id: 250, text: 'Televisión', icon: 'bi bi-tv', category: 'Objetos de la casa' },
    { id: 251, text: 'Teléfono', icon: 'bi bi-phone', category: 'Objetos de la casa' },
    { id: 252, text: 'Ordenador', icon: 'bi bi-laptop', category: 'Objetos de la casa' },
    { id: 253, text: 'Puerta', icon: 'bi bi-door-open', category: 'Objetos de la casa' },
    { id: 254, text: 'Ventana', icon: 'bi bi-window', category: 'Objetos de la casa' },
    { id: 255, text: 'Baño', icon: 'bi bi-toilet', category: 'Objetos de la casa' },
    { id: 256, text: 'Cocina', icon: 'bi bi-oven', category: 'Objetos de la casa' },
    { id: 257, text: 'Jardín', icon: 'bi bi-tree', category: 'Objetos de la casa' },

    // Material escolar
    { id: 258, text: 'Lápiz', icon: 'bi bi-pencil', category: 'Material escolar' },
    { id: 259, text: 'Goma', icon: 'bi bi-eraser', category: 'Material escolar' },
    { id: 260, text: 'Sacapuntas', icon: 'bi bi-pencil-square', category: 'Material escolar' },
    { id: 261, text: 'Regla', icon: 'bi bi-rulers', category: 'Material escolar' },
    { id: 262, text: 'Tijeras', icon: 'bi bi-scissors', category: 'Material escolar' },
    { id: 263, text: 'Pegamento', icon: 'bi bi-paperclip', category: 'Material escolar' },
    { id: 264, text: 'Libro', icon: 'bi bi-book', category: 'Material escolar' },
    { id: 265, text: 'Cuaderno', icon: 'bi bi-journal-bookmark', category: 'Material escolar' },
    { id: 266, text: 'Mochila', icon: 'bi bi-backpack', category: 'Material escolar' },
    { id: 267, text: 'Pizarra', icon: 'bi bi-easel', category: 'Material escolar' },

    // Bebidas
    { id: 268, text: 'Agua', icon: 'bi bi-cup-straw', category: 'Bebidas' },
    { id: 269, text: 'Leche', icon: 'bi bi-cup-straw', category: 'Bebidas' },
    { id: 270, text: 'Jugo', icon: 'bi bi-cup-straw', category: 'Bebidas' },
    { id: 271, text: 'Refresco', icon: 'bi bi-cup-straw', category: 'Bebidas' },
    { id: 272, text: 'Té', icon: 'bi bi-cup-straw', category: 'Bebidas' },
    { id: 273, text: 'Café', icon: 'bi bi-cup-straw', category: 'Bebidas' },

    // Postres
    { id: 274, text: 'Pastel', icon: 'bi bi-cake', category: 'Postres' },
    { id: 275, text: 'Helado', icon: 'bi bi-ice-cream', category: 'Postres' },
    { id: 276, text: 'Galleta', icon: 'bi bi-cookie', category: 'Postres' },
    { id: 277, text: 'Chocolate', icon: 'bi bi-chocolate', category: 'Postres' },
    { id: 278, text: 'Caramelo', icon: 'bi bi-candy', category: 'Postres' },
    { id: 279, text: 'Fruta', icon: 'bi bi-apple', category: 'Postres' },

    // Instrumentos musicales
    { id: 280, text: 'Guitarra', icon: 'bi bi-guitar', category: 'Instrumentos musicales' },
    { id: 281, text: 'Piano', icon: 'bi bi-piano', category: 'Instrumentos musicales' },
    { id: 282, text: 'Batería', icon: 'bi bi-drums', category: 'Instrumentos musicales' },
    { id: 283, text: 'Violín', icon: 'bi bi-violin', category: 'Instrumentos musicales' },
    { id: 284, text: 'Trompeta', icon: 'bi bi-trumpet', category: 'Instrumentos musicales' },
    { id: 285, text: 'Flauta', icon: 'bi bi-flute', category: 'Instrumentos musicales' },

    // Deportes
    { id: 286, text: 'Fútbol', icon: 'bi bi-football', category: 'Deportes' },
    { id: 287, text: 'Baloncesto', icon: 'bi bi-basketball', category: 'Deportes' },
    { id: 288, text: 'Béisbol', icon: 'bi bi-baseball', category: 'Deportes' },
    { id: 289, text: 'Tenis', icon: 'bi bi-tennis-racket', category: 'Deportes' },
    { id: 290, text: 'Natación', icon: 'bi bi-person-arms-up', category: 'Deportes' },
    { id: 291, text: 'Atletismo', icon: 'bi bi-person-running', category: 'Deportes' },
    { id: 292, text: 'Ciclismo', icon: 'bi bi-bicycle', category: 'Deportes' },

    // Sentimientos
    { id: 293, text: 'Amor', icon: 'bi bi-heart', category: 'Sentimientos' },
    { id: 294, text: 'Amistad', icon: 'bi bi-people', category: 'Sentimientos' },
    { id: 295, text: 'Alegría', icon: 'bi bi-emoji-laughing', category: 'Sentimientos' },
    { id: 296, text: 'Tristeza', icon: 'bi bi-emoji-dizzy', category: 'Sentimientos' },
    { id: 297, text: 'Miedo', icon: 'bi bi-emoji-scream', category: 'Sentimientos' },
    { id: 298, text: 'Ira', icon: 'bi bi-emoji-angry', category: 'Sentimientos' },
    { id: 299, text: 'Sorpresa', icon: 'bi bi-emoji-surprise', category: 'Sentimientos' },
    { id: 300, text: 'Confianza', icon: 'bi bi-person-check', category: 'Sentimientos' },
    { id: 301, text: 'Vergüenza', icon: 'bi bi-person-exclamation', category: 'Sentimientos' },
];
