const pictograms = [
    // Acciones y Verbos
    { id: 1, text: 'Correr', icon: 'twemoji:running-shoe', category: 'Acciones y Verbos' },
    { id: 2, text: 'Saltar', icon: 'mdi:human-jump', category: 'Acciones y Verbos' },
    { id: 3, text: 'Nadar', icon: 'mdi:swim', category: 'Acciones y Verbos' },
    { id: 4, text: 'Escribir', icon: 'mdi:pencil', category: 'Acciones y Verbos' },
    { id: 5, text: 'Leer', icon: 'mdi:book-open-page-variant', category: 'Acciones y Verbos' },
    { id: 6, text: 'Cantar', icon: 'mdi:microphone', category: 'Acciones y Verbos' },
    { id: 7, text: 'Bailar', icon: 'mdi:human-female-dance', category: 'Acciones y Verbos' },
    { id: 8, text: 'Dormir', icon: 'mdi:sleep', category: 'Acciones y Verbos' },
    { id: 9, text: 'Despertar', icon: 'mdi:weather-sunset-up', category: 'Acciones y Verbos' },
    { id: 10, text: 'Abrazar', icon: 'mdi:human-greeting-variant', category: 'Acciones y Verbos' },
    { id: 11, text: 'Besar', icon: 'mdi:human-kiss', category: 'Acciones y Verbos' },
    { id: 12, text: 'Llorar', icon: 'emojione:crying-face', category: 'Acciones y Verbos' },
    { id: 13, text: 'Reír', icon: 'emojione:smiling-face-with-smiling-eyes', category: 'Acciones y Verbos' },
    { id: 14, text: 'Jugar', icon: 'mdi:gamepad-variant', category: 'Acciones y Verbos' },
    { id: 15, text: 'Comer', icon: 'mdi:food-fork-drink', category: 'Acciones y Verbos' },
    { id: 16, text: 'Beber', icon: 'mdi:glass-cocktail', category: 'Acciones y Verbos' },
    { id: 17, text: 'Ir', icon: 'mdi:walk', category: 'Acciones y Verbos' },
    { id: 18, text: 'Ver', icon: 'mdi:eye', category: 'Acciones y Verbos' },
    { id: 19, text: 'Escuchar', icon: 'mdi:ear-hearing', category: 'Acciones y Verbos' },
    { id: 20, text: 'Hablar', icon: 'mdi:message-text', category: 'Acciones y Verbos' },
    { id: 21, text: 'Pensar', icon: 'mdi:brain', category: 'Acciones y Verbos' },
    { id: 22, text: 'Sentir', icon: 'mdi:heart', category: 'Acciones y Verbos' },
    { id: 23, text: 'Ayudar', icon: 'mdi:human-handsup', category: 'Acciones y Verbos' },
    { id: 24, text: 'Trabajar', icon: 'mdi:briefcase', category: 'Acciones y Verbos' },
    { id: 25, text: 'Estudiar', icon: 'mdi:book-open-variant', category: 'Acciones y Verbos' },

    // Animales
    { id: 26, text: 'Perro', icon: 'emojione:dog-face', category: 'Animales' },
    { id: 27, text: 'Gato', icon: 'emojione:cat-face', category: 'Animales' },
    { id: 28, text: 'Pájaro', icon: 'emojione:bird', category: 'Animales' },
    { id: 29, text: 'Pez', icon: 'emojione:fish', category: 'Animales' },
    { id: 30, text: 'Caballo', icon: 'emojione:horse-face', category: 'Animales' },
    { id: 31, text: 'Vaca', icon: 'emojione:cow-face', category: 'Animales' },
    { id: 32, text: 'León', icon: 'emojione:lion-face', category: 'Animales' },
    { id: 33, text: 'Tigre', icon: 'emojione:tiger-face', category: 'Animales' },
    { id: 34, text: 'Oso', icon: 'emojione:bear-face', category: 'Animales' },
    { id: 35, text: 'Elefante', icon: 'emojione:elephant', category: 'Animales' },
    { id: 36, text: 'Jirafa', icon: 'emojione:giraffe-face', category: 'Animales' },
    { id: 37, text: 'Mono', icon: 'emojione:monkey-face', category: 'Animales' },
    { id: 38, text: 'Serpiente', icon: 'emojione:snake', category: 'Animales' },
    { id: 39, text: 'Cocodrilo', icon: 'emojione:crocodile', category: 'Animales' },
    { id: 40, text: 'Rana', icon: 'emojione:frog-face', category: 'Animales' },
    { id: 41, text: 'Mariposa', icon: 'emojione:butterfly', category: 'Animales' },
    { id: 42, text: 'Abeja', icon: 'emojione:honeybee', category: 'Animales' },
    { id: 43, text: 'Araña', icon: 'emojione:spider', category: 'Animales' },
    { id: 44, text: 'Delfín', icon: 'emojione:dolphin', category: 'Animales' },
    { id: 45, text: 'Ballena', icon: 'emojione:whale', category: 'Animales' },

    // Comida
    { id: 46, text: 'Manzana', icon: 'emojione:red-apple', category: 'Comida' },
    { id: 47, text: 'Plátano', icon: 'emojione:banana', category: 'Comida' },
    { id: 48, text: 'Naranja', icon: 'emojione:tangerine', category: 'Comida' },
    { id: 49, text: 'Fresa', icon: 'emojione:strawberry', category: 'Comida' },
    { id: 50, text: 'Uva', icon: 'emojione:grapes', category: 'Comida' },
    { id: 51, text: 'Sandía', icon: 'emojione:watermelon', category: 'Comida' },
    { id: 52, text: 'Pan', icon: 'emojione:bread', category: 'Comida' },
    { id: 53, text: 'Queso', icon: 'emojione:cheese-wedge', category: 'Comida' },
    { id: 54, text: 'Huevo', icon: 'emojione:egg', category: 'Comida' },
    { id: 55, text: 'Pollo', icon: 'emojione:poultry-leg', category: 'Comida' },
    { id: 56, text: 'Carne', icon: 'emojione:meat-on-bone', category: 'Comida' },
    { id: 57, text: 'Pescado', icon: 'emojione:fish', category: 'Comida' },
    { id: 58, text: 'Arroz', icon: 'emojione:cooked-rice', category: 'Comida' },
    { id: 59, text: 'Pasta', icon: 'emojione:spaghetti', category: 'Comida' },
    { id: 60, text: 'Pizza', icon: 'emojione:pizza', category: 'Comida' },
    { id: 61, text: 'Hamburguesa', icon: 'emojione:hamburger', category: 'Comida' },
    { id: 62, text: 'Papas fritas', icon: 'emojione:french-fries', category: 'Comida' },
    { id: 63, text: 'Helado', icon: 'emojione:ice-cream', category: 'Comida' },
    { id: 64, text: 'Pastel', icon: 'emojione:birthday-cake', category: 'Comida' },
    { id: 65, text: 'Galleta', icon: 'emojione:cookie', category: 'Comida' },
    { id: 66, text: 'Leche', icon: 'emojione:glass-of-milk', category: 'Comida' },
    { id: 67, text: 'Jugo', icon: 'emojione:tropical-drink', category: 'Comida' },
    { id: 68, text: 'Agua', icon: 'emojione:potable-water', category: 'Comida' },

    // Ropa
    { id: 69, text: 'Camisa', icon: 'emojione:t-shirt', category: 'Ropa' },
    { id: 70, text: 'Pantalón', icon: 'emojione:jeans', category: 'Ropa' },
    { id: 71, text: 'Vestido', icon: 'emojione:dress', category: 'Ropa' },
    { id: 72, text: 'Falda', icon: 'emojione:womans-clothes', category: 'Ropa' },
    { id: 73, text: 'Zapatos', icon: 'emojione:mans-shoe', category: 'Ropa' },
    { id: 74, text: 'Calcetines', icon: 'emojione:socks', category: 'Ropa' },
    { id: 75, text: 'Sombrero', icon: 'emojione:womans-hat', category: 'Ropa' },
    { id: 76, text: 'Chaqueta', icon: 'emojione:jacket', category: 'Ropa' },
    { id: 77, text: 'Gafas', icon: 'emojione:eyeglasses', category: 'Ropa' },

    // Partes del cuerpo
    { id: 78, text: 'Cabeza', icon: 'emojione:bust-in-silhouette', category: 'Partes del cuerpo' },
    { id: 79, text: 'Ojo', icon: 'emojione:eye', category: 'Partes del cuerpo' },
    { id: 80, text: 'Nariz', icon: 'emojione:nose', category: 'Partes del cuerpo' },
    { id: 81, text: 'Boca', icon: 'emojione:mouth', category: 'Partes del cuerpo' },
    { id: 82, text: 'Oreja', icon: 'emojione:ear', category: 'Partes del cuerpo' },
    { id: 83, text: 'Mano', icon: 'emojione:raised-hand', category: 'Partes del cuerpo' },
    { id: 84, text: 'Pie', icon: 'emojione:footprints', category: 'Partes del cuerpo' },
    { id: 85, text: 'Brazo', icon: 'emojione:flexed-biceps', category: 'Partes del cuerpo' },
    { id: 86, text: 'Pierna', icon: 'emojione:leg', category: 'Partes del cuerpo' },
    { id: 87, text: 'Pelo', icon: 'emojione:haircut', category: 'Partes del cuerpo' },

    // Lugares
    { id: 88, text: 'Casa', icon: 'emojione:house', category: 'Lugares' },
    { id: 89, text: 'Escuela', icon: 'emojione:school', category: 'Lugares' },
    { id: 90, text: 'Parque', icon: 'emojione:national-park', category: 'Lugares' },
    { id: 91, text: 'Tienda', icon: 'emojione:convenience-store', category: 'Lugares' },
    { id: 92, text: 'Hospital', icon: 'emojione:hospital', category: 'Lugares' },
    { id: 93, text: 'Playa', icon: 'emojione:beach-with-umbrella', category: 'Lugares' },
    { id: 94, text: 'Cine', icon: 'emojione:movie-camera', category: 'Lugares' },
    { id: 95, text: 'Restaurante', icon: 'emojione:fork-and-knife-with-plate', category: 'Lugares' },
    { id: 96, text: 'Supermercado', icon: 'emojione:shopping-cart', category: 'Lugares' },
    { id: 97, text: 'Zoológico', icon: 'emojione:zoo', category: 'Lugares' },
    { id: 98, text: 'Biblioteca', icon: 'emojione:books', category: 'Lugares' },
    { id: 99, text: 'Iglesia', icon: 'emojione:church', category: 'Lugares' },
    { id: 100, text: 'Montaña', icon: 'emojione:mountain', category: 'Lugares' },
    { id: 101, text: 'Río', icon: 'emojione:water-wave', category: 'Lugares' },
    { id: 102, text: 'Mar', icon: 'emojione:ocean', category: 'Lugares' },

    // Emociones
    { id: 103, text: 'Feliz', icon: 'emojione:grinning-face-with-smiling-eyes', category: 'Emociones' },
    { id: 104, text: 'Triste', icon: 'emojione:sad-but-relieved-face', category: 'Emociones' },
    { id: 105, text: 'Enojado', icon: 'emojione:pouting-face', category: 'Emociones' },
    { id: 106, text: 'Asustado', icon: 'emojione:face-screaming-in-fear', category: 'Emociones' },
    { id: 107, text: 'Sorprendido', icon: 'emojione:astonished-face', category: 'Emociones' },
    { id: 108, text: 'Cansado', icon: 'emojione:tired-face', category: 'Emociones' },
    { id: 109, text: 'Aburrido', icon: 'emojione:unamused-face', category: 'Emociones' },
    { id: 110, text: 'Enamorado', icon: 'emojione:smiling-face-with-heart-eyes', category: 'Emociones' },
    { id: 111, text: 'Contento', icon: 'emojione:smiling-face', category: 'Emociones' },

    // Colores
    { id: 112, text: 'Rojo', icon: 'emojione:red-circle', category: 'Colores' },
    { id: 113, text: 'Azul', icon: 'emojione:blue-circle', category: 'Colores' },
    { id: 114, text: 'Verde', icon: 'emojione:green-circle', category: 'Colores' },
    { id: 115, text: 'Amarillo', icon: 'emojione:yellow-circle', category: 'Colores' },
    { id: 116, text: 'Naranja', icon: 'emojione:orange-circle', category: 'Colores' },
    { id: 117, text: 'Morado', icon: 'emojione:purple-circle', category: 'Colores' },
    { id: 118, text: 'Rosa', icon: 'emojione:pink-circle', category: 'Colores' },
    { id: 119, text: 'Blanco', icon: 'emojione:white-circle', category: 'Colores' },
    { id: 120, text: 'Negro', icon: 'emojione:black-circle', category: 'Colores' },
    { id: 121, text: 'Gris', icon: 'emojione:grey-circle', category: 'Colores' },
    { id: 122, text: 'Marrón', icon: 'emojione:brown-circle', category: 'Colores' },

    // Números
    { id: 123, text: 'Uno', icon: 'emojione:keycap-1', category: 'Números' },
    { id: 124, text: 'Dos', icon: 'emojione:keycap-2', category: 'Números' },
    { id: 125, text: 'Tres', icon: 'emojione:keycap-3', category: 'Números' },
    { id: 126, text: 'Cuatro', icon: 'emojione:keycap-4', category: 'Números' },
    { id: 127, text: 'Cinco', icon: 'emojione:keycap-5', category: 'Números' },
    { id: 128, text: 'Seis', icon: 'emojione:keycap-6', category: 'Números' },
    { id: 129, text: 'Siete', icon: 'emojione:keycap-7', category: 'Números' },
    { id: 130, text: 'Ocho', icon: 'emojione:keycap-8', category: 'Números' },
    { id: 131, text: 'Nueve', icon: 'emojione:keycap-9', category: 'Números' },
    { id: 132, text: 'Diez', icon: 'emojione:keycap-10', category: 'Números' },

    // Familia
    { id: 133, text: 'Mamá', icon: 'emojione:woman', category: 'Familia' },
    { id: 134, text: 'Papá', icon: 'emojione:man', category: 'Familia' },
    { id: 135, text: 'Hermano', icon: 'emojione:boy', category: 'Familia' },
    { id: 136, text: 'Hermana', icon: 'emojione:girl', category: 'Familia' },
    { id: 137, text: 'Abuelo', icon: 'emojione:old-man', category: 'Familia' },
    { id: 138, text: 'Abuela', icon: 'emojione:old-woman', category: 'Familia' },
    { id: 139, text: 'Bebé', icon: 'emojione:baby', category: 'Familia' },

    // Juguetes
    { id: 140, text: 'Pelota', icon: 'emojione:soccer-ball', category: 'Juguetes' },
    { id: 141, text: 'Muñeca', icon: 'emojione:dolls', category: 'Juguetes' },
    { id: 142, text: 'Coche', icon: 'emojione:automobile', category: 'Juguetes' },
    { id: 143, text: 'Tren', icon: 'emojione:train', category: 'Juguetes' },
    { id: 144, text: 'Avión', icon: 'emojione:airplane', category: 'Juguetes' },
    { id: 145, text: 'Barco', icon: 'emojione:speedboat', category: 'Juguetes' },
    { id: 146, text: 'Bicicleta', icon: 'emojione:bicycle', category: 'Juguetes' },
    { id: 147, text: 'Bloques', icon: 'emojione:bricks', category: 'Juguetes' },
    { id: 148, text: 'Rompecabezas', icon: 'emojione:puzzle-piece', category: 'Juguetes' },

    // Naturaleza
    { id: 149, text: 'Sol', icon: 'emojione:sun', category: 'Naturaleza' },
    { id: 150, text: 'Luna', icon: 'emojione:moon', category: 'Naturaleza' },
    { id: 151, text: 'Estrella', icon: 'emojione:star', category: 'Naturaleza' },
    { id: 152, text: 'Árbol', icon: 'emojione:deciduous-tree', category: 'Naturaleza' },
    { id: 153, text: 'Flor', icon: 'emojione:hibiscus', category: 'Naturaleza' },
    { id: 154, text: 'Nube', icon: 'emojione:cloud', category: 'Naturaleza' },
    { id: 155, text: 'Lluvia', icon: 'emojione:cloud-with-rain', category: 'Naturaleza' },
    { id: 156, text: 'Nieve', icon: 'emojione:cloud-with-snow', category: 'Naturaleza' },
    { id: 157, text: 'Viento', icon: 'emojione:wind-face', category: 'Naturaleza' },
    { id: 158, text: 'Fuego', icon: 'emojione:fire', category: 'Naturaleza' },

    // Profesiones
    { id: 159, text: 'Doctor', icon: 'emojione:health-worker-man', category: 'Profesiones' },
    { id: 160, text: 'Enfermera', icon: 'emojione:health-worker-woman', category: 'Profesiones' },
    { id: 161, text: 'Maestro', icon: 'emojione:teacher-man', category: 'Profesiones' },
    { id: 162, text: 'Policía', icon: 'emojione:police-officer', category: 'Profesiones' },
    { id: 163, text: 'Bombero', icon: 'emojione:firefighter', category: 'Profesiones' },
    { id: 164, text: 'Cocinero', icon: 'emojione:cook', category: 'Profesiones' },
    { id: 165, text: 'Piloto', icon: 'emojione:pilot', category: 'Profesiones' },
    { id: 166, text: 'Músico', icon: 'emojione:musical-score', category: 'Profesiones' },
    { id: 167, text: 'Pintor', icon: 'emojione:artist-palette', category: 'Profesiones' },
    { id: 168, text: 'Carpintero', icon: 'emojione:hammer-and-wrench', category: 'Profesiones' },

    // Transporte
    { id: 169, text: 'Coche', icon: 'emojione:oncoming-automobile', category: 'Transporte' },
    { id: 170, text: 'Autobús', icon: 'emojione:bus', category: 'Transporte' },
    { id: 171, text: 'Tren', icon: 'emojione:light-rail', category: 'Transporte' },
    { id: 172, text: 'Avión', icon: 'emojione:small-airplane', category: 'Transporte' },
    { id: 173, text: 'Barco', icon: 'emojione:sailboat', category: 'Transporte' },
    { id: 174, text: 'Bicicleta', icon: 'emojione:bicycle', category: 'Transporte' },
    { id: 175, text: 'Moto', icon: 'emojione:motorcycle', category: 'Transporte' },
    { id: 176, text: 'Taxi', icon: 'emojione:oncoming-taxi', category: 'Transporte' },
    { id: 177, text: 'Ambulancia', icon: 'emojione:ambulance', category: 'Transporte' },
    { id: 178, text: 'Camión de bomberos', icon: 'emojione:fire-engine', category: 'Transporte' },

    // Adjetivos
    { id: 179, text: 'Grande', icon: 'emojione:magnifying-glass-tilted-right', category: 'Adjetivos' },
    { id: 180, text: 'Pequeño', icon: 'emojione:magnifying-glass-tilted-left', category: 'Adjetivos' },
    { id: 181, text: 'Alto', icon: 'emojione:up-arrow', category: 'Adjetivos' },
    { id: 182, text: 'Bajo', icon: 'emojione:down-arrow', category: 'Adjetivos' },
    { id: 183, text: 'Rápido', icon: 'emojione:fast-forward-button', category: 'Adjetivos' },
    { id: 184, text: 'Lento', icon: 'emojione:fast-reverse-button', category: 'Adjetivos' },
    { id: 185, text: 'Caliente', icon: 'emojione:hot-beverage', category: 'Adjetivos' },
    { id: 186, text: 'Frío', icon: 'emojione:snowflake', category: 'Adjetivos' },
    { id: 187, text: 'Limpio', icon: 'emojione:soap', category: 'Adjetivos' },
    { id: 188, text: 'Sucio', icon: 'emojione:pile-of-poo', category: 'Adjetivos' },
    { id: 189, text: 'Duro', icon: 'emojione:gem-stone', category: 'Adjetivos' },
    { id: 190, text: 'Blando', icon: 'emojione:cushion', category: 'Adjetivos' },
    { id: 191, text: 'Bonito', icon: 'emojione:smiling-face-with-three-hearts', category: 'Adjetivos' },
    { id: 192, text: 'Feo', icon: 'emojione:pouting-cat-face', category: 'Adjetivos' },

    // Conceptos
    { id: 193, text: 'Sí', icon: 'emojione:check-mark-button', category: 'Conceptos' },
    { id: 194, text: 'No', icon: 'emojione:cross-mark', category: 'Conceptos' },
    { id: 195, text: 'Hola', icon: 'emojione:waving-hand', category: 'Conceptos' },
    { id: 196, text: 'Adiós', icon: 'emojione:waving-hand', category: 'Conceptos' },
    { id: 197, text: 'Por favor', icon: 'emojione:folded-hands', category: 'Conceptos' },
    { id: 198, text: 'Gracias', icon: 'emojione:handshake', category: 'Conceptos' },
    { id: 199, text: 'Lo siento', icon: 'emojione:disappointed-face', category: 'Conceptos' },
    { id: 200, text: 'Ayuda', icon: 'emojione:sos-button', category: 'Conceptos' },
    { id: 201, text: 'Más', icon: 'emojione:plus', category: 'Conceptos' },
    { id: 202, text: 'Menos', icon: 'emojione:minus', category: 'Conceptos' },
    { id: 203, text: 'Igual', icon: 'emojione:heavy-equals-sign', category: 'Conceptos' },
    { id: 204, text: 'Diferente', icon: 'emojione:wavy-dash', category: 'Conceptos' },
    { id: 205, text: 'Ahora', icon: 'emojione:alarm-clock', category: 'Conceptos' },
    { id: 206, text: 'Después', icon: 'emojione:hourglass-done', category: 'Conceptos' },
    { id: 207, text: 'Antes', icon: 'emojione:hourglass-not-done', category: 'Conceptos' },

    // Preguntas
    { id: 208, text: '¿Qué?', icon: 'emojione:question-mark', category: 'Preguntas' },
    { id: 209, text: '¿Quién?', icon: 'emojione:question-mark', category: 'Preguntas' },
    { id: 210, text: '¿Cuándo?', icon: 'emojione:question-mark', category: 'Preguntas' },
    { id: 211, text: '¿Dónde?', icon: 'emojione:question-mark', category: 'Preguntas' },
    { id: 212, text: '¿Por qué?', icon: 'emojione:question-mark', category: 'Preguntas' },
    { id: 213, text: '¿Cómo?', icon: 'emojione:question-mark', category: 'Preguntas' },

    // Formas
    { id: 214, text: 'Círculo', icon: 'emojione:red-circle', category: 'Formas' },
    { id: 215, text: 'Cuadrado', icon: 'emojione:black-square-button', category: 'Formas' },
    { id: 216, text: 'Triángulo', icon: 'emojione:up-pointing-red-triangle', category: 'Formas' },
    { id: 217, text: 'Rectángulo', icon: 'emojione:black-medium-square', category: 'Formas' },
    { id: 218, text: 'Estrella', icon: 'emojione:star', category: 'Formas' },
    { id: 219, text: 'Corazón', icon: 'emojione:red-heart', category: 'Formas' },

    // Días de la semana
    { id: 220, text: 'Lunes', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 221, text: 'Martes', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 222, text: 'Miércoles', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 223, text: 'Jueves', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 224, text: 'Viernes', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 225, text: 'Sábado', icon: 'emojione:calendar', category: 'Días de la semana' },
    { id: 226, text: 'Domingo', icon: 'emojione:calendar', category: 'Días de la semana' },

    // Meses del año
    { id: 227, text: 'Enero', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 228, text: 'Febrero', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 229, text: 'Marzo', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 230, text: 'Abril', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 231, text: 'Mayo', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 232, text: 'Junio', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 233, text: 'Julio', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 234, text: 'Agosto', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 235, text: 'Septiembre', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 236, text: 'Octubre', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 237, text: 'Noviembre', icon: 'emojione:spiral-calendar', category: 'Meses del año' },
    { id: 238, text: 'Diciembre', icon: 'emojione:spiral-calendar', category: 'Meses del año' },

    // Clima
    { id: 239, text: 'Soleado', icon: 'emojione:sun-with-face', category: 'Clima' },
    { id: 240, text: 'Nublado', icon: 'emojione:cloud', category: 'Clima' },
    { id: 241, text: 'Lluvioso', icon: 'emojione:cloud-with-rain', category: 'Clima' },
    { id: 242, text: 'Nevando', icon: 'emojione:cloud-with-snow', category: 'Clima' },
    { id: 243, text: 'Viento', icon: 'emojione:wind-face', category: 'Clima' },
    { id: 244, text: 'Tormenta', icon: 'emojione:cloud-with-lightning-and-rain', category: 'Clima' },

    // Objetos de la casa
    { id: 245, text: 'Mesa', icon: 'mdi:table-furniture', category: 'Objetos de la casa' },
    { id: 246, text: 'Silla', icon: 'mdi:chair-rolling', category: 'Objetos de la casa' },
    { id: 247, text: 'Cama', icon: 'mdi:bed', category: 'Objetos de la casa' },
    { id: 248, text: 'Sofá', icon: 'mdi:sofa', category: 'Objetos de la casa' },
    { id: 249, text: 'Lámpara', icon: 'mdi:lamp', category: 'Objetos de la casa' },
    { id: 250, text: 'Televisión', icon: 'mdi:television', category: 'Objetos de la casa' },
    { id: 251, text: 'Teléfono', icon: 'mdi:phone', category: 'Objetos de la casa' },
    { id: 252, text: 'Ordenador', icon: 'mdi:laptop', category: 'Objetos de la casa' },
    { id: 253, text: 'Puerta', icon: 'mdi:door', category: 'Objetos de la casa' },
    { id: 254, text: 'Ventana', icon: 'mdi:window-closed', category: 'Objetos de la casa' },
    { id: 255, text: 'Baño', icon: 'mdi:toilet', category: 'Objetos de la casa' },
    { id: 256, text: 'Cocina', icon: 'mdi:silverware-fork-knife', category: 'Objetos de la casa' },
    { id: 257, text: 'Jardín', icon: 'mdi:flower', category: 'Objetos de la casa' },

    // Material escolar
    { id: 258, text: 'Lápiz', icon: 'mdi:pencil', category: 'Material escolar' },
    { id: 259, text: 'Goma', icon: 'mdi:eraser', category: 'Material escolar' },
    { id: 260, text: 'Sacapuntas', icon: 'mdi:pencil-box', category: 'Material escolar' },
    { id: 261, text: 'Regla', icon: 'mdi:ruler', category: 'Material escolar' },
    { id: 262, text: 'Tijeras', icon: 'mdi:content-cut', category: 'Material escolar' },
    { id: 263, text: 'Pegamento', icon: 'mdi:glue', category: 'Material escolar' },
    { id: 264, text: 'Libro', icon: 'mdi:book-open', category: 'Material escolar' },
    { id: 265, text: 'Cuaderno', icon: 'mdi:notebook', category: 'Material escolar' },
    { id: 266, text: 'Mochila', icon: 'mdi:briefcase', category: 'Material escolar' },
    { id: 267, text: 'Pizarra', icon: 'mdi:chalkboard', category: 'Material escolar' },

    // Bebidas
    { id: 268, text: 'Agua', icon: 'mdi:cup-water', category: 'Bebidas' },
    { id: 269, text: 'Leche', icon: 'mdi:cup', category: 'Bebidas' },
    { id: 270, text: 'Jugo', icon: 'mdi:glass-cocktail', category: 'Bebidas' },
    { id: 271, text: 'Refresco', icon: 'mdi:bottle-soda-classic', category: 'Bebidas' },
    { id: 272, text: 'Té', icon: 'mdi:tea', category: 'Bebidas' },
    { id: 273, text: 'Café', icon: 'mdi:coffee', category: 'Bebidas' },

    // Postres
    { id: 274, text: 'Pastel', icon: 'mdi:cake-variant', category: 'Postres' },
    { id: 275, text: 'Helado', icon: 'mdi:ice-cream', category: 'Postres' },
    { id: 276, text: 'Galleta', icon: 'mdi:cookie', category: 'Postres' },
    { id: 277, text: 'Chocolate', icon: 'mdi:chocolate', category: 'Postres' },
    { id: 278, text: 'Caramelo', icon: 'mdi:candycane', category: 'Postres' },
    { id: 279, text: 'Fruta', icon: 'mdi:food-apple', category: 'Postres' },

    // Instrumentos musicales
    { id: 280, text: 'Guitarra', icon: 'mdi:guitar-acoustic', category: 'Instrumentos musicales' },
    { id: 281, text: 'Piano', icon: 'mdi:piano', category: 'Instrumentos musicales' },
    { id: 282, text: 'Batería', icon: 'mdi:drum', category: 'Instrumentos musicales' },
    { id: 283, text: 'Violín', icon: 'mdi:violin', category: 'Instrumentos musicales' },
    { id: 284, text: 'Trompeta', icon: 'mdi:trumpet', category: 'Instrumentos musicales' },
    { id: 285, text: 'Flauta', icon: 'mdi:flute', category: 'Instrumentos musicales' },

    // Deportes
    { id: 286, text: 'Fútbol', icon: 'mdi:soccer', category: 'Deportes' },
    { id: 287, text: 'Baloncesto', icon: 'mdi:basketball', category: 'Deportes' },
    { id: 288, text: 'Béisbol', icon: 'mdi:baseball-bat', category: 'Deportes' },
    { id: 289, text: 'Tenis', icon: 'mdi:tennis', category: 'Deportes' },
    { id: 290, text: 'Natación', icon: 'mdi:swim', category: 'Deportes' },
    { id: 291, text: 'Atletismo', icon: 'mdi:run', category: 'Deportes' },
    { id: 292, text: 'Ciclismo', icon: 'mdi:bike', category: 'Deportes' },

    // Sentimientos
    { id: 293, text: 'Amor', icon: 'mdi:heart', category: 'Sentimientos' },
    { id: 294, text: 'Amistad', icon: 'mdi:account-group', category: 'Sentimientos' },
    { id: 295, text: 'Alegría', icon: 'mdi:emoticon-happy', category: 'Sentimientos' },
    { id: 296, text: 'Tristeza', icon: 'mdi:emoticon-sad', category: 'Sentimientos' },
    { id: 297, text: 'Miedo', icon: 'mdi:emoticon-dead', category: 'Sentimientos' },
    { id: 298, text: 'Ira', icon: 'mdi:emoticon-angry', category: 'Sentimientos' },
    { id: 299, text: 'Sorpresa', icon: 'mdi:emoticon-excited', category: 'Sentimientos' },
    { id: 300, text: 'Confianza', icon: 'mdi:account-heart', category: 'Sentimientos' },
    { id: 301, text: 'Vergüenza', icon: 'mdi:emoticon-cry', category: 'Sentimientos' },
];
